---
name: Catalyst-View-HTML-Template-Compiled
version: 0.11
author:
  - 'Sascha Kiefer, C<esskar@cpan.org>'
abstract: HTML::Template::Compiled View Class
license: perl
requires:
  Catalyst: 5
  HTML::Template::Compiled: 0.53
  Path::Class: 0.10
provides:
  Catalyst::Helper::View::HTML::Template::Compiled:
    file: lib/Catalyst/Helper/View/HTML/Template/Compiled.pm
    version: 0.03
  Catalyst::View::HTML::Template::Compiled:
    file: lib/Catalyst/View/HTML/Template/Compiled.pm
    version: 0.11
generated_by: Module::Build version 0.2611
